ARG IMAGE_REGISTRY=ghcr.io/toppers
ARG ASSET_SUFFIX=-demo
ARG TAG=latest
FROM --platform=linux/amd64 ${IMAGE_REGISTRY}/hakoniwa-ecu-multiplay${ASSET_SUFFIX}:${TAG} AS hakoniwa-ecu-multiplay-demo

# If you want to build docker image, you can see dockerfile in 'hako/docker/Dockerfile'.
