ARG IMAGE_REGISTRY
ARG HAKONIWA_VERSION
FROM --platform=linux/amd64 ${IMAGE_REGISTRY}/hakoniwa-ecu-multiplay:${HAKONIWA_VERSION}

# If you want to build docker image, you can see dockerfile in 'hako/docker/Dockerfile'.
